name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the dependencies
        run: |
          python -m pip install -r website_notebook/requirements.txt
          python -m pip install wheel
          python -m pip install setuptools
      - name: Create a wheel for the python files
        run: |
          cd analyze-tblgen
          python -m build
      - name: Put the wheel in the notebook files
        run: |
          cp analyze-tblgen/dist/*.whl website_notebook/files/
      - name: Build the site
        run: |
          cd website_notebook
          jupyter lite build
      - name: Upload (dist)
        uses: actions/upload-artifact@v2
        with:
          name: analyze-tablegen dist ${{ github.run_number }}
          path: ./website_notebook/_output

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: actions/download-artifact@v2
        with:
          name: analyze-tablegen dist ${{ github.run_number }}
          path: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist